// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductServiceApp.Infrastructure.Database.Contexts;

#nullable disable

namespace ProductServiceApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260504145351_AddProductTypeRelation")]
    partial class AddProductTypeRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbSchemaGoodHamburger")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductServiceApp.Domain.Entities.Orders.OrderAuditEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 100000L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_date");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("tb_orders_audit", "dbSchemaGoodHamburger");
                });

            modelBuilder.Entity("ProductServiceApp.Domain.Entities.Orders.OrderDiscountRuleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 100000L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_date");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_date");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<bool>("HasFries")
                        .HasColumnType("boolean")
                        .HasColumnName("has_fries");

                    b.Property<bool>("HasRefreshment")
                        .HasColumnType("boolean")
                        .HasColumnName("has_refreshment");

                    b.Property<bool>("HasSandwich")
                        .HasColumnType("boolean")
                        .HasColumnName("has_sandwich");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("HasSandwich", "HasFries", "HasRefreshment")
                        .IsUnique()
                        .HasFilter("is_deleted <> true");

                    b.ToTable("tb_order_discount_rule", "dbSchemaGoodHamburger");

                    b.HasData(
                        new
                        {
                            Id = 100000L,
                            DiscountPercentage = 20m,
                            HasFries = true,
                            HasRefreshment = true,
                            HasSandwich = true,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 100001L,
                            DiscountPercentage = 15m,
                            HasFries = false,
                            HasRefreshment = true,
                            HasSandwich = true,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 100002L,
                            DiscountPercentage = 10m,
                            HasFries = true,
                            HasRefreshment = false,
                            HasSandwich = true,
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ProductServiceApp.Domain.Entities.Orders.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 100000L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_date");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_date");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("discount_value");

                    b.Property<long?>("IdOrdersAudit")
                        .HasColumnType("bigint")
                        .HasColumnName("id_orders_audit");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("SubTotalValue")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal_value");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_value");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdersAudit");

                    b.ToTable("tb_order", "dbSchemaGoodHamburger");
                });

            modelBuilder.Entity("ProductServiceApp.Domain.Entities.Orders.OrderProductEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("tb_order_product", "dbSchemaGoodHamburger");
                });

            modelBuilder.Entity("ProductServiceApp.Domain.Entities.Products.ProductEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 100000L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("tb_product", "dbSchemaGoodHamburger");

                    b.HasData(
                        new
                        {
                            Id = 100000L,
                            CreatedByUserId = 1L,
                            CreatedDate = new DateTime(2026, 4, 29, 23, 12, 12, 284, DateTimeKind.Utc).AddTicks(3527),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Batata frita",
                            Price = 2m,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 100001L,
                            CreatedByUserId = 1L,
                            CreatedDate = new DateTime(2026, 4, 29, 23, 12, 12, 284, DateTimeKind.Utc).AddTicks(3947),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "X Burger",
                            Price = 5m,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 100002L,
                            CreatedByUserId = 1L,
                            CreatedDate = new DateTime(2026, 4, 29, 23, 12, 12, 284, DateTimeKind.Utc).AddTicks(4127),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "X Egg",
                            Price = 4.50m,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 100003L,
                            CreatedByUserId = 1L,
                            CreatedDate = new DateTime(2026, 4, 29, 23, 12, 12, 284, DateTimeKind.Utc).AddTicks(4131),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "X Bacon",
                            Price = 7m,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 100004L,
                            CreatedByUserId = 1L,
                            CreatedDate = new DateTime(2026, 4, 29, 23, 12, 12, 284, DateTimeKind.Utc).AddTicks(4133),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Refrigerante",
                            Price = 2.50m,
                            Type = (byte)3
                        });
                });

            modelBuilder.Entity("ProductServiceApp.Domain.Entities.Products.ProductTypeEntity", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("tb_product_type", "dbSchemaGoodHamburger");

                    b.HasData(
                        new
                        {
                            Id = (byte)0,
                            Description = "Nao definido"
                        },
                        new
                        {
                            Id = (byte)1,
                            Description = "Sanduiche"
                        },
                        new
                        {
                            Id = (byte)2,
                            Description = "Batata frita"
                        },
                        new
                        {
                            Id = (byte)3,
                            Description = "Refrigerante"
                        });
                });

            modelBuilder.Entity("ProductServiceApp.Domain.Entities.Orders.OrderEntity", b =>
                {
                    b.HasOne("ProductServiceApp.Domain.Entities.Orders.OrderAuditEntity", "OrdersAudit")
                        .WithMany()
                        .HasForeignKey("IdOrdersAudit")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrdersAudit");
                });

            modelBuilder.Entity("ProductServiceApp.Domain.Entities.Orders.OrderProductEntity", b =>
                {
                    b.HasOne("ProductServiceApp.Domain.Entities.Orders.OrderEntity", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductServiceApp.Domain.Entities.Products.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductServiceApp.Domain.Entities.Products.ProductEntity", b =>
                {
                    b.HasOne("ProductServiceApp.Domain.Entities.Products.ProductTypeEntity", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("ProductServiceApp.Domain.Entities.Orders.OrderEntity", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("ProductServiceApp.Domain.Entities.Products.ProductTypeEntity", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
