#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${POSTGRES_KEYCLOAK_USER} WITH PASSWORD '${POSTGRES_KEYCLOAK_PASSWORD}';
    CREATE DATABASE ${POSTGRES_KEYCLOAK_DB} OWNER ${POSTGRES_KEYCLOAK_USER};
EOSQL
