#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_REPLICATION_USER}') THEN
            CREATE USER ${POSTGRES_REPLICATION_USER} WITH REPLICATION ENCRYPTED PASSWORD '${POSTGRES_REPLICATION_PASSWORD}';
        END IF;

        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_READ_USER}') THEN
            CREATE USER ${POSTGRES_READ_USER} WITH ENCRYPTED PASSWORD '${POSTGRES_READ_PASSWORD}';
        END IF;
    END
    \$\$;

    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_READ_USER};
    CREATE SCHEMA IF NOT EXISTS "dbSchemaGoodHamburger";
    GRANT USAGE ON SCHEMA "dbSchemaGoodHamburger" TO ${POSTGRES_READ_USER};
    GRANT SELECT ON ALL TABLES IN SCHEMA "dbSchemaGoodHamburger" TO ${POSTGRES_READ_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA "dbSchemaGoodHamburger" GRANT SELECT ON TABLES TO ${POSTGRES_READ_USER};
    GRANT USAGE ON SCHEMA public TO ${POSTGRES_READ_USER};
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_READ_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${POSTGRES_READ_USER};
EOSQL
