networks:
  6137_webnet:
    driver: bridge

services:

  # ─── PRIMARY ───────────────────────────────────────────────
  6137_postgres_primary:
    image: postgres:17
    container_name: 6137_postgres_primary
    restart: always
    environment:
      POSTGRES_USER: randandan
      POSTGRES_PASSWORD: randandan_XLR
      POSTGRES_DB: dbproducts
    volumes:
      - 6137_pgdata_primary:/var/lib/postgresql/data
      - ./primary/postgresql.conf:/etc/primary/postgresql.conf
      - ./primary/pg_hba.conf:/etc/primary/pg_hba.conf
      - ./init:/docker-entrypoint-initdb.d
    command: >
      postgres
        -c config_file=/etc/primary/postgresql.conf
        -c hba_file=/etc/primary/pg_hba.conf
    ports:
      - "9000:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U randandan -d dbproducts"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - 6137_webnet

  # ─── REPLICA ───────────────────────────────────────────────
  6137_postgres_replica:
    image: postgres:17
    container_name: 6137_postgres_replica
    user: postgres
    volumes:
      - 6137_pgdata_replica:/var/lib/postgresql/data
      - ./replica/postgresql.conf:/etc/replica/postgresql.conf
      - ./replica/replica-entrypoint.sh:/replica-entrypoint.sh
    entrypoint: ["/bin/bash", "/replica-entrypoint.sh"]
    ports:
      - "9001:5433"
    depends_on:
      6137_postgres_primary:
        condition: service_healthy
    networks:
      - 6137_webnet

  # ─── API ────────────────────────────────────────────────────
  6137_api_product_service:
    build:
      context: ..
      dockerfile: deploy-docker/Dockerfile
    container_name: 6137_api_product_service
    ports:
      - "9005:9005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Port=9005
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ConnectionStrings__PostgresWrite=Server=6137_postgres_primary;Port=5432;Database=dbproducts;Username=randandan;Password=randandan_XLR;
      - ConnectionStrings__PostgresRead=Server=6137_postgres_replica;Port=5433;Database=dbproducts;Username=read_randandan;Password=read_randandan_XLR;
    depends_on:
      6137_postgres_primary:
        condition: service_healthy
    networks:
      - 6137_webnet

volumes:
  6137_pgdata_primary:
  6137_pgdata_replica: